[2025-01-26T16:51:00.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T16:51:00.410+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt_postgres.load_to_postgres scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-26T16:51:00.417+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt_postgres.load_to_postgres scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-26T16:51:00.418+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T16:51:00.444+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-01-24 00:00:00+00:00
[2025-01-26T16:51:00.455+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt_postgres', 'load_to_postgres', 'scheduled__2025-01-24T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_postgres.py', '--cfg-path', '/tmp/tmp_u7ug1ic']
[2025-01-26T16:51:00.459+0000] {standard_task_runner.py:105} INFO - Job 77: Subtask load_to_postgres
[2025-01-26T16:51:00.463+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-26T16:51:00.464+0000] {standard_task_runner.py:72} INFO - Started process 752 to run task
[2025-01-26T16:51:00.535+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt_postgres.load_to_postgres scheduled__2025-01-24T00:00:00+00:00 [running]> on host b597abfab341
[2025-01-26T16:51:00.623+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Temp_elt_postgres' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-24T00:00:00+00:00'
[2025-01-26T16:51:00.624+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T16:51:00.657+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:51:00.667+0000] {sql.py:553} INFO - Running statement: 
    INSERT INTO processed_weather_data (location, region, country, lat, lon, "localtime",
       temperature_c, temperature_f, feelslike_c, feelslike_f, date)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
    , parameters: ('Gwagwaldda', 'Federal Capital Territory', 'Nigeria', 8.9414, 7.0919, '2025-01-22 11:45', 33.2, 91.8, 31.1, 87.9, datetime.date(2025, 1, 22))
[2025-01-26T16:51:00.670+0000] {sql.py:562} INFO - Rows affected: 1
[2025-01-26T16:51:00.675+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T16:51:00.683+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T16:51:00.683+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt_postgres, task_id=load_to_postgres, run_id=scheduled__2025-01-24T00:00:00+00:00, execution_date=20250124T000000, start_date=20250126T165100, end_date=20250126T165100
[2025-01-26T16:51:00.734+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T16:51:00.755+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T16:51:00.757+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
