[2025-02-01T20:00:37.810+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T20:00:37.831+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-01T20:00:37.844+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-01T20:00:37.844+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-02-01T20:00:37.882+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2025-01-30 00:00:00+00:00
[2025-02-01T20:00:37.887+0000] {standard_task_runner.py:72} INFO - Started process 463 to run task
[2025-02-01T20:00:37.892+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2025-01-30T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmphugzb49q']
[2025-02-01T20:00:37.895+0000] {standard_task_runner.py:105} INFO - Job 112: Subtask delete_data_from_table
[2025-02-01T20:00:37.997+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-30T00:00:00+00:00 [running]> on host ba586a51095f
[2025-02-01T20:00:38.126+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-30T00:00:00+00:00'
[2025-02-01T20:00:38.128+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T20:00:38.159+0000] {sql.py:278} INFO - Executing: 
            delete from dag_runs where dt = '2025-01-30' and dag_id = 'dag_with_postgres_operator_v03';
        
[2025-02-01T20:00:38.174+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-01T20:00:38.282+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-02-01T20:00:38.300+0000] {sql.py:553} INFO - Running statement: 
            delete from dag_runs where dt = '2025-01-30' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2025-02-01T20:00:38.305+0000] {sql.py:562} INFO - Rows affected: 0
[2025-02-01T20:00:38.318+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T20:00:38.319+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, run_id=scheduled__2025-01-30T00:00:00+00:00, execution_date=20250130T000000, start_date=20250201T200037, end_date=20250201T200038
[2025-02-01T20:00:38.362+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T20:00:38.396+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-01T20:00:38.404+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
