[2025-02-03T14:58:40.759+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-03T14:58:40.787+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data manual__2025-02-03T14:58:13.427590+00:00 [queued]>
[2025-02-03T14:58:40.802+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Temp_elt_postgres.extract_weather_data manual__2025-02-03T14:58:13.427590+00:00 [queued]>
[2025-02-03T14:58:40.804+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-03T14:58:40.850+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_weather_data> on 2025-02-03 14:58:13.427590+00:00
[2025-02-03T14:58:40.863+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'Temp_elt_postgres', 'extract_weather_data', 'manual__2025-02-03T14:58:13.427590+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_postgres.py', '--cfg-path', '/tmp/tmpgriauhwm']
[2025-02-03T14:58:40.868+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask extract_weather_data
[2025-02-03T14:58:40.869+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=148) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-03T14:58:40.871+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2025-02-03T14:58:41.040+0000] {task_command.py:467} INFO - Running <TaskInstance: Temp_elt_postgres.extract_weather_data manual__2025-02-03T14:58:13.427590+00:00 [running]> on host 9591593ff695
[2025-02-03T14:58:41.189+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Temp_elt_postgres' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T14:58:13.427590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-03T14:58:13.427590+00:00'
[2025-02-03T14:58:41.191+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-03T14:58:42.358+0000] {logging_mixin.py:190} INFO - {'message': 'Invalid API key. Go to https://docs.rapidapi.com/docs/keys for more info.'}
[2025-02-03T14:58:42.373+0000] {logging_mixin.py:190} INFO -                                              message
0  Invalid API key. Go to https://docs.rapidapi.c...
[2025-02-03T14:58:42.375+0000] {logging_mixin.py:190} INFO - undexpected error: {e}
[2025-02-03T14:58:42.377+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-03T14:58:42.390+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-03T14:58:42.392+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Temp_elt_postgres, task_id=extract_weather_data, run_id=manual__2025-02-03T14:58:13.427590+00:00, execution_date=20250203T145813, start_date=20250203T145840, end_date=20250203T145842
[2025-02-03T14:58:42.452+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-03T14:58:42.507+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-03T14:58:42.517+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
