[2025-01-11T11:40:26.080+0100] {processor.py:186} INFO - Started process (PID=13499) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:40:26.087+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:40:26.088+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:40:26.088+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:40:29.464+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736591957, 'localtime': '2025-01-11 11:39'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:40:29.528+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:40:29.543+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:40:29.794+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:40:29.795+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:40:29.795+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:40:29.822+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:40:29.823+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:40:29.823+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:40:29.850+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:40:29.851+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:40:29.851+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:40:29.879+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:40:29.880+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:40:29.880+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:40:29.909+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:40:29.910+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:40:29.982+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:40:30.288+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:40:30.288+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:40:30.332+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:40:30.332+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-07 00:00:00+00:00, run_after=2025-01-08 00:00:00+00:00
[2025-01-11T11:40:30.359+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 4.295 seconds
[2025-01-11T11:45:31.324+0100] {processor.py:186} INFO - Started process (PID=15133) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:31.331+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:45:31.333+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:31.333+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:33.191+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:45:33.216+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:45:33.219+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:45:33.297+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:33.297+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:33.297+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:45:33.320+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:33.320+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:33.321+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:45:33.341+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:33.342+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:33.342+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:45:33.361+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:33.362+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:33.362+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:45:33.385+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:33.386+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:33.387+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:45:33.409+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:33.409+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:33.410+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:45:33.437+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:33.437+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:33.450+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:33.584+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:33.583+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-03T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:45:33.664+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:45:33.665+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:44:48.151838+00:00 end:2025-01-11 10:45:33.588623+00:00 duration:45.436785
[2025-01-11T11:45:33.665+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-03 00:00:00+00:00: scheduled__2025-01-03T00:00:00+00:00, state:running, queued_at: 2025-01-07 20:03:35.919852+00:00. externally triggered: False>
[2025-01-11T11:45:33.666+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-03T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:45:33.667+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:33.667+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-03T00:00:00+00:00, execution_date=20250103T000000, start_date=20250111T104448, end_date=20250111T104533
[2025-01-11T11:45:33.683+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:33.682+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-03T00:00:00+00:00 [failed]> in state failed
[2025-01-11T11:45:33.710+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:33.709+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:45:33.796+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:33.796+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-08 00:00:00+00:00, run_after=2025-01-09 00:00:00+00:00
[2025-01-11T11:45:33.821+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.506 seconds
[2025-01-11T11:45:37.982+0100] {processor.py:186} INFO - Started process (PID=15156) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:37.988+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:45:37.990+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:37.989+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:39.862+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:45:39.889+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:45:39.891+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:45:39.952+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:39.953+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:39.953+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:45:39.976+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:39.977+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:39.977+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:45:39.994+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:39.995+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:39.995+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:45:40.011+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:40.011+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:40.012+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:45:40.031+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:40.032+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:40.033+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:45:40.050+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:40.050+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:40.051+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:45:40.066+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:40.067+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:40.080+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:40.196+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:40.196+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-04T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:45:40.266+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:45:40.267+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:44:55.946158+00:00 end:2025-01-11 10:45:40.200673+00:00 duration:44.254515
[2025-01-11T11:45:40.267+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-04 00:00:00+00:00: scheduled__2025-01-04T00:00:00+00:00, state:running, queued_at: 2025-01-07 20:04:02.026844+00:00. externally triggered: False>
[2025-01-11T11:45:40.267+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-04T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:45:40.268+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:40.268+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-04T00:00:00+00:00, execution_date=20250104T000000, start_date=20250111T104455, end_date=20250111T104540
[2025-01-11T11:45:40.284+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:40.283+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-04T00:00:00+00:00 [failed]> in state failed
[2025-01-11T11:45:40.306+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:40.305+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:45:40.390+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:40.390+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-09 00:00:00+00:00, run_after=2025-01-10 00:00:00+00:00
[2025-01-11T11:45:40.414+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.439 seconds
[2025-01-11T11:45:44.509+0100] {processor.py:186} INFO - Started process (PID=15192) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:44.516+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:45:44.518+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:44.518+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:46.545+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:45:46.569+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:45:46.572+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:45:46.641+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:46.641+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:46.642+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:45:46.670+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:46.671+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:46.671+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:45:46.692+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:46.693+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:46.693+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:45:46.715+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:46.715+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:46.716+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:45:46.737+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:46.738+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:46.738+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:45:46.760+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:46.760+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:46.761+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:45:46.787+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:46.788+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:46.800+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:46.946+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:46.946+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-07T20:04:05.836170+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:45:47.023+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:45:47.024+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:26.529589+00:00 end:2025-01-11 10:45:46.952348+00:00 duration:20.422759
[2025-01-11T11:45:47.024+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-07 20:04:05.836170+00:00: manual__2025-01-07T20:04:05.836170+00:00, state:running, queued_at: 2025-01-07 20:04:05.879571+00:00. externally triggered: True>
[2025-01-11T11:45:47.025+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-07T20:04:05.836170+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:45:47.025+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:47.025+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Temp_elt, task_id=extract_weather_data, run_id=manual__2025-01-07T20:04:05.836170+00:00, execution_date=20250107T200405, start_date=20250111T104526, end_date=20250111T104546
[2025-01-11T11:45:47.039+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:47.038+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data manual__2025-01-07T20:04:05.836170+00:00 [failed]> in state failed
[2025-01-11T11:45:47.065+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:47.064+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:45:47.165+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:47.164+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-09 00:00:00+00:00, run_after=2025-01-10 00:00:00+00:00
[2025-01-11T11:45:47.192+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.691 seconds
[2025-01-11T11:45:51.413+0100] {processor.py:186} INFO - Started process (PID=15231) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:51.420+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:45:51.422+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:51.422+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:53.328+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:45:53.351+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:45:53.353+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:45:53.414+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:53.415+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:53.415+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:45:53.438+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:53.439+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:53.439+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:45:53.457+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:53.458+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:53.458+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:45:53.477+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:53.477+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:53.477+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:45:53.496+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:53.496+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:53.496+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:45:53.511+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:53.512+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:53.512+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:45:53.533+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:53.533+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:53.542+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:53.683+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:53.683+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-05T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:45:53.770+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:45:53.770+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:04.092272+00:00 end:2025-01-11 10:45:53.689126+00:00 duration:49.596854
[2025-01-11T11:45:53.771+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-05 00:00:00+00:00: scheduled__2025-01-05T00:00:00+00:00, state:running, queued_at: 2025-01-07 20:04:18.206302+00:00. externally triggered: False>
[2025-01-11T11:45:53.771+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-05T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:45:53.772+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:53.771+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-05T00:00:00+00:00, execution_date=20250105T000000, start_date=20250111T104504, end_date=20250111T104553
[2025-01-11T11:45:53.787+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:53.787+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-05T00:00:00+00:00 [failed]> in state failed
[2025-01-11T11:45:53.813+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:53.812+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:45:53.903+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:53.902+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-09 00:00:00+00:00, run_after=2025-01-10 00:00:00+00:00
[2025-01-11T11:45:53.928+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.523 seconds
[2025-01-11T11:45:58.046+0100] {processor.py:186} INFO - Started process (PID=15265) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:58.053+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:45:58.055+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:45:58.054+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:45:59.857+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:45:59.886+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:45:59.889+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:45:59.949+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:59.949+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:59.950+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:45:59.973+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:59.974+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:59.974+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:45:59.993+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:45:59.994+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:45:59.994+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:00.011+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:00.011+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:00.011+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:00.033+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:00.033+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:00.033+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:00.050+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:00.051+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:00.051+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:00.067+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:00.068+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:00.081+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:00.197+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:00.196+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-06T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:00.270+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:00.270+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:11.429244+00:00 end:2025-01-11 10:46:00.201329+00:00 duration:48.772085
[2025-01-11T11:46:00.270+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-06 00:00:00+00:00: scheduled__2025-01-06T00:00:00+00:00, state:running, queued_at: 2025-01-07 20:04:44.989242+00:00. externally triggered: False>
[2025-01-11T11:46:00.271+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-06T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:00.271+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:00.271+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-06T00:00:00+00:00, execution_date=20250106T000000, start_date=20250111T104511, end_date=20250111T104600
[2025-01-11T11:46:00.286+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:00.285+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-06T00:00:00+00:00 [failed]> in state failed
[2025-01-11T11:46:00.310+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:00.310+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:00.393+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:00.393+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-10 00:00:00+00:00, run_after=2025-01-11 00:00:00+00:00
[2025-01-11T11:46:00.414+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.376 seconds
[2025-01-11T11:46:04.337+0100] {processor.py:186} INFO - Started process (PID=15301) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:04.344+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:46:04.346+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:04.346+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:06.080+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:46:06.103+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:46:06.105+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:46:06.165+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:06.165+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:06.166+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:46:06.187+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:06.188+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:06.188+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:46:06.205+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:06.205+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:06.205+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:06.221+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:06.222+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:06.222+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:06.242+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:06.243+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:06.243+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:06.258+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:06.259+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:06.259+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:06.279+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:06.279+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:06.289+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:06.406+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:06.405+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-07T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:06.490+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:06.490+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:18.999456+00:00 end:2025-01-11 10:46:06.484890+00:00 duration:47.485434
[2025-01-11T11:46:06.490+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-07 00:00:00+00:00: scheduled__2025-01-07T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:44:40.655392+00:00. externally triggered: False>
[2025-01-11T11:46:06.491+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-07T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:06.491+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:06.491+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-07T00:00:00+00:00, execution_date=20250107T000000, start_date=20250111T104518, end_date=20250111T104606
[2025-01-11T11:46:06.505+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:06.505+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-07T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:46:06.532+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:06.529+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:06.609+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:06.609+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-10 00:00:00+00:00, run_after=2025-01-11 00:00:00+00:00
[2025-01-11T11:46:06.633+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.307 seconds
[2025-01-11T11:46:14.602+0100] {processor.py:186} INFO - Started process (PID=15357) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:14.610+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:46:14.612+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:14.611+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:16.870+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592343, 'localtime': '2025-01-11 11:45'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:46:16.896+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:46:16.898+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:46:16.960+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:16.961+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:16.961+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:46:16.982+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:16.982+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:16.983+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:46:16.999+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:16.999+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:16.999+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:46:17.019+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:17.019+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:17.020+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:17.039+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:17.040+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:17.041+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:17.057+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:17.058+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:17.058+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:17.076+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:17.077+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:17.077+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:17.094+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:17.094+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:17.103+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:17.267+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:17.267+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-05T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:17.362+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:17.362+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:04.092272+00:00 end:2025-01-11 10:46:17.274791+00:00 duration:73.182519
[2025-01-11T11:46:17.362+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-05 00:00:00+00:00: scheduled__2025-01-05T00:00:00+00:00, state:failed, queued_at: 2025-01-07 20:04:18.206302+00:00. externally triggered: False>
[2025-01-11T11:46:17.363+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-05T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:17.363+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:17.363+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-05T00:00:00+00:00, execution_date=20250105T000000, start_date=20250111T104504, end_date=20250111T104617
[2025-01-11T11:46:17.381+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:17.380+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-05T00:00:00+00:00 [failed]> in state failed
[2025-01-11T11:46:17.406+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:17.406+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:17.499+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:17.499+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:46:17.527+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.934 seconds
[2025-01-11T11:46:21.496+0100] {processor.py:186} INFO - Started process (PID=15391) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:21.502+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:46:21.503+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:21.503+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:23.309+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:46:23.334+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:46:23.336+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:46:23.396+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:23.397+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:23.397+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:46:23.414+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:23.415+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:23.415+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:46:23.437+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:23.438+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:23.438+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:46:23.454+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:23.455+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:23.455+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:23.472+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:23.473+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:23.473+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:23.492+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:23.492+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:23.493+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:23.509+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:23.509+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:23.510+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:23.528+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:23.528+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:23.539+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:23.656+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:23.655+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-06T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:23.737+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:23.737+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:11.429244+00:00 end:2025-01-11 10:46:23.660513+00:00 duration:72.231269
[2025-01-11T11:46:23.737+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-06 00:00:00+00:00: scheduled__2025-01-06T00:00:00+00:00, state:running, queued_at: 2025-01-07 20:04:44.989242+00:00. externally triggered: False>
[2025-01-11T11:46:23.737+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-06T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:23.738+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:23.738+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-06T00:00:00+00:00, execution_date=20250106T000000, start_date=20250111T104511, end_date=20250111T104623
[2025-01-11T11:46:23.750+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:23.750+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-06T00:00:00+00:00 [failed]> in state failed
[2025-01-11T11:46:23.777+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:23.776+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:23.860+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:23.859+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:46:23.918+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.430 seconds
[2025-01-11T11:46:27.556+0100] {processor.py:186} INFO - Started process (PID=15433) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:27.562+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:46:27.563+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:27.563+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:29.401+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:46:29.425+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:46:29.428+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:46:29.489+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:29.490+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:29.490+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:46:29.507+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:29.507+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:29.508+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:46:29.531+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:29.531+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:29.531+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:46:29.548+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:29.549+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:29.549+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:29.567+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:29.567+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:29.567+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:29.589+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:29.589+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:29.589+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:29.606+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:29.607+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:29.607+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:29.625+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:29.626+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:29.637+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:29.754+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:29.754+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-07T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:29.834+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:29.834+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:18.999456+00:00 end:2025-01-11 10:46:29.759669+00:00 duration:70.760213
[2025-01-11T11:46:29.834+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-07 00:00:00+00:00: scheduled__2025-01-07T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:44:40.655392+00:00. externally triggered: False>
[2025-01-11T11:46:29.834+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-07T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:29.835+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:29.835+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-07T00:00:00+00:00, execution_date=20250107T000000, start_date=20250111T104518, end_date=20250111T104629
[2025-01-11T11:46:29.845+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:29.845+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-07T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:46:29.866+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:29.866+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:29.946+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:29.946+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:46:29.969+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.420 seconds
[2025-01-11T11:46:33.630+0100] {processor.py:186} INFO - Started process (PID=15457) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:33.638+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:46:33.640+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:33.639+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:35.359+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:46:35.387+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:46:35.388+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:46:35.447+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:35.447+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:35.448+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:46:35.463+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:35.464+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:35.464+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:46:35.487+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:35.488+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:35.488+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:46:35.505+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:35.506+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:35.506+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:35.522+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:35.522+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:35.523+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:35.541+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:35.542+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:35.542+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:35.559+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:35.560+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:35.560+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:35.580+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:35.580+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:35.591+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:35.711+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:35.711+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-11T10:44:43.193601+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:35.789+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:35.790+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:50.458187+00:00 end:2025-01-11 10:46:35.784601+00:00 duration:45.326414
[2025-01-11T11:46:35.790+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-11 10:44:43.193601+00:00: manual__2025-01-11T10:44:43.193601+00:00, state:running, queued_at: 2025-01-11 10:44:43.243426+00:00. externally triggered: True>
[2025-01-11T11:46:35.790+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-11T10:44:43.193601+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:35.791+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:35.791+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=manual__2025-01-11T10:44:43.193601+00:00, execution_date=20250111T104443, start_date=20250111T104550, end_date=20250111T104635
[2025-01-11T11:46:35.807+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:35.807+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data manual__2025-01-11T10:44:43.193601+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:46:35.835+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:35.833+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:35.921+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:35.921+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:46:35.947+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.325 seconds
[2025-01-11T11:46:39.556+0100] {processor.py:186} INFO - Started process (PID=15494) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:39.564+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:46:39.566+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:39.566+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:41.376+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:46:41.400+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:46:41.402+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:46:41.464+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:41.464+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:41.464+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:46:41.486+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:41.486+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:41.486+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:46:41.505+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:41.506+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:41.506+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:46:41.524+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:41.524+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:41.525+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:41.544+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:41.544+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:41.544+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:41.560+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:41.560+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:41.560+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:41.580+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:41.580+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:41.581+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:41.596+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:41.597+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:41.607+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:41.744+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:41.743+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-08T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:41.840+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:41.840+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:41.807729+00:00 end:2025-01-11 10:46:41.833706+00:00 duration:60.025977
[2025-01-11T11:46:41.840+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-08 00:00:00+00:00: scheduled__2025-01-08T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:45:34.160106+00:00. externally triggered: False>
[2025-01-11T11:46:41.841+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-08T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:41.841+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:41.841+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250111T104541, end_date=20250111T104641
[2025-01-11T11:46:41.855+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:41.854+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-08T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:46:41.884+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:41.882+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:41.965+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:41.965+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:46:41.991+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.443 seconds
[2025-01-11T11:46:49.939+0100] {processor.py:186} INFO - Started process (PID=15554) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:49.945+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:46:49.947+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:49.947+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:51.768+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:46:51.797+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:46:51.799+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:46:51.868+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:51.868+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:51.869+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:46:51.890+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:51.890+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:51.891+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:46:51.913+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:51.913+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:51.914+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:46:51.936+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:51.937+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:51.937+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:51.955+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:51.955+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:51.956+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:51.974+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:51.974+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:51.974+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:51.996+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:51.996+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:51.996+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:52.013+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:52.014+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:52.028+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:52.154+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:52.153+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-07T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:52.233+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:52.233+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:18.999456+00:00 end:2025-01-11 10:46:52.159111+00:00 duration:93.159655
[2025-01-11T11:46:52.233+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-07 00:00:00+00:00: scheduled__2025-01-07T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:44:40.655392+00:00. externally triggered: False>
[2025-01-11T11:46:52.234+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-07T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:52.234+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:52.234+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-07T00:00:00+00:00, execution_date=20250107T000000, start_date=20250111T104518, end_date=20250111T104652
[2025-01-11T11:46:52.244+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:52.244+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-07T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:46:52.273+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:52.272+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:52.361+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:52.361+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:46:52.389+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.458 seconds
[2025-01-11T11:46:56.381+0100] {processor.py:186} INFO - Started process (PID=15579) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:56.388+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:46:56.389+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:56.389+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:58.410+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:46:58.439+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:46:58.441+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:46:58.506+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:58.507+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:58.507+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:46:58.528+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:58.528+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:58.529+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:46:58.550+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:58.551+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:58.551+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:46:58.569+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:58.570+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:58.571+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:46:58.591+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:58.591+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:58.592+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:46:58.610+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:58.610+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:58.610+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:46:58.631+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:58.632+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:58.632+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:46:58.648+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:46:58.648+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:46:58.659+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:46:58.790+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:58.789+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-11T10:44:43.193601+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:58.854+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:46:58.855+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:50.458187+00:00 end:2025-01-11 10:46:58.796443+00:00 duration:68.338256
[2025-01-11T11:46:58.855+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-11 10:44:43.193601+00:00: manual__2025-01-11T10:44:43.193601+00:00, state:running, queued_at: 2025-01-11 10:44:43.243426+00:00. externally triggered: True>
[2025-01-11T11:46:58.855+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-11T10:44:43.193601+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:46:58.855+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:58.855+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=manual__2025-01-11T10:44:43.193601+00:00, execution_date=20250111T104443, start_date=20250111T104550, end_date=20250111T104658
[2025-01-11T11:46:58.866+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:58.865+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data manual__2025-01-11T10:44:43.193601+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:46:58.892+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:58.891+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:46:58.981+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:46:58.980+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:46:59.002+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.630 seconds
[2025-01-11T11:47:02.516+0100] {processor.py:186} INFO - Started process (PID=15612) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:02.523+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:47:02.525+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:02.525+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:04.154+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:47:04.180+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:47:04.183+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:47:04.309+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:04.310+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:04.310+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:47:04.335+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:04.336+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:04.336+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:47:04.359+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:04.359+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:04.359+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:47:04.380+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:04.380+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:04.381+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:47:04.401+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:04.402+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:04.402+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:47:04.422+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:04.423+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:04.423+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:47:04.440+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:04.440+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:04.441+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:47:04.455+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:04.455+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:04.466+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:04.575+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:04.574+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-08T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:04.646+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:47:04.646+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:41.807729+00:00 end:2025-01-11 10:47:04.581523+00:00 duration:82.773794
[2025-01-11T11:47:04.646+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-08 00:00:00+00:00: scheduled__2025-01-08T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:45:34.160106+00:00. externally triggered: False>
[2025-01-11T11:47:04.646+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-08T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:04.647+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:04.647+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250111T104541, end_date=20250111T104704
[2025-01-11T11:47:04.656+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:04.656+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-08T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:47:04.682+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:04.682+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:47:04.755+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:04.755+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:47:04.778+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.269 seconds
[2025-01-11T11:47:08.369+0100] {processor.py:186} INFO - Started process (PID=15645) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:08.377+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:47:08.378+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:08.378+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:10.097+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592215, 'localtime': '2025-01-11 11:43'}, 'current': {'last_updated_epoch': 1736591400, 'last_updated': '2025-01-11 11:30', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:47:10.122+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:47:10.125+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:47:10.190+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:10.191+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:10.191+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:47:10.207+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:10.207+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:10.207+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:47:10.230+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:10.231+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:10.231+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:47:10.248+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:10.249+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:10.250+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:47:10.266+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:10.266+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:10.267+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:47:10.288+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:10.288+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:10.288+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:47:10.306+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:10.307+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:10.307+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:47:10.326+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:10.326+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:10.337+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:10.446+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:10.445+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-09T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:10.531+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:47:10.531+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:46:01.891303+00:00 end:2025-01-11 10:47:10.523080+00:00 duration:68.631777
[2025-01-11T11:47:10.532+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-09 00:00:00+00:00: scheduled__2025-01-09T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:45:54.277357+00:00. externally triggered: False>
[2025-01-11T11:47:10.532+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-09T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:10.533+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:10.532+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-09T00:00:00+00:00, execution_date=20250109T000000, start_date=20250111T104601, end_date=20250111T104710
[2025-01-11T11:47:10.546+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:10.546+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-09T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:47:10.576+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:10.574+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:47:10.662+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:10.661+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:47:10.688+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.326 seconds
[2025-01-11T11:47:22.652+0100] {processor.py:186} INFO - Started process (PID=15714) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:22.658+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:47:22.659+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:22.659+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:26.019+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592374, 'localtime': '2025-01-11 11:46'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:47:26.043+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:47:26.045+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:47:26.101+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.102+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.102+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:47:26.120+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.120+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.120+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:47:26.140+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.141+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.141+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:47:26.155+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.156+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.156+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:47:26.172+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.172+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.172+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:47:26.190+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.191+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.191+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:47:26.209+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.210+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.210+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:47:26.228+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.229+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.229+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:47:26.244+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:26.245+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:26.255+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:26.362+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:26.361+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-11T10:44:43.193601+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:26.436+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:47:26.437+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:50.458187+00:00 end:2025-01-11 10:47:26.366429+00:00 duration:95.908242
[2025-01-11T11:47:26.437+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-11 10:44:43.193601+00:00: manual__2025-01-11T10:44:43.193601+00:00, state:running, queued_at: 2025-01-11 10:44:43.243426+00:00. externally triggered: True>
[2025-01-11T11:47:26.437+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'manual__2025-01-11T10:44:43.193601+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:26.437+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:26.437+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=manual__2025-01-11T10:44:43.193601+00:00, execution_date=20250111T104443, start_date=20250111T104550, end_date=20250111T104726
[2025-01-11T11:47:26.447+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:26.447+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data manual__2025-01-11T10:44:43.193601+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:47:26.475+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:26.474+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:47:26.605+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:26.604+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:47:26.635+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 3.990 seconds
[2025-01-11T11:47:30.012+0100] {processor.py:186} INFO - Started process (PID=15772) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:30.018+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:47:30.020+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:30.019+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:32.130+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592374, 'localtime': '2025-01-11 11:46'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:47:32.151+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:47:32.153+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:47:32.216+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.216+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.217+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:47:32.237+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.238+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.238+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:47:32.253+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.253+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.254+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:47:32.270+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.270+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.270+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:47:32.289+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.290+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.290+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:47:32.307+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.308+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.308+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:47:32.324+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.324+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.325+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:47:32.343+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.343+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.343+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:47:32.358+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:32.359+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:32.369+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:32.493+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:32.492+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-08T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:32.568+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:47:32.568+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:45:41.807729+00:00 end:2025-01-11 10:47:32.498199+00:00 duration:110.69047
[2025-01-11T11:47:32.568+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-08 00:00:00+00:00: scheduled__2025-01-08T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:45:34.160106+00:00. externally triggered: False>
[2025-01-11T11:47:32.569+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-08T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:32.569+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:32.569+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-08T00:00:00+00:00, execution_date=20250108T000000, start_date=20250111T104541, end_date=20250111T104732
[2025-01-11T11:47:32.584+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:32.583+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-08T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:47:32.607+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:32.607+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:47:32.693+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:32.693+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:47:32.717+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.712 seconds
[2025-01-11T11:47:36.716+0100] {processor.py:186} INFO - Started process (PID=15796) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:36.723+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:47:36.725+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:36.725+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:38.585+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592374, 'localtime': '2025-01-11 11:46'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:47:38.609+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:47:38.611+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:47:38.681+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.682+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.682+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:47:38.699+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.699+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.699+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:47:38.719+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.719+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.720+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:47:38.742+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.742+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.742+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:47:38.758+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.759+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.759+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:47:38.778+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.779+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.779+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:47:38.795+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.795+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.796+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:47:38.812+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.812+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.812+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:47:38.834+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:38.834+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:38.845+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:38.966+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:38.965+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-09T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:39.045+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:47:39.046+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:46:01.891303+00:00 end:2025-01-11 10:47:38.972827+00:00 duration:97.081524
[2025-01-11T11:47:39.046+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-09 00:00:00+00:00: scheduled__2025-01-09T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:45:54.277357+00:00. externally triggered: False>
[2025-01-11T11:47:39.046+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-09T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:39.047+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:39.047+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-09T00:00:00+00:00, execution_date=20250109T000000, start_date=20250111T104601, end_date=20250111T104738
[2025-01-11T11:47:39.058+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:39.058+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-09T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:47:39.084+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:39.084+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:47:39.165+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:39.165+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:47:39.190+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.483 seconds
[2025-01-11T11:47:42.889+0100] {processor.py:186} INFO - Started process (PID=15828) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:42.896+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:47:42.897+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:42.897+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:44.726+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592374, 'localtime': '2025-01-11 11:46'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:47:44.749+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:47:44.751+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:47:44.815+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.816+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.816+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:47:44.838+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.838+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.839+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:47:44.854+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.855+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.855+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:47:44.872+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.873+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.874+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:47:44.892+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.892+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.892+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:47:44.910+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.910+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.911+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:47:44.929+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.930+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.930+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:47:44.947+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.948+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.948+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:47:44.963+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:47:44.963+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:47:44.976+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:47:45.093+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:45.093+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-10T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:45.168+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:47:45.169+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:46:18.672699+00:00 end:2025-01-11 10:47:45.161633+00:00 duration:86.488934
[2025-01-11T11:47:45.169+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-10 00:00:00+00:00: scheduled__2025-01-10T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:46:10.994270+00:00. externally triggered: False>
[2025-01-11T11:47:45.169+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-10T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:47:45.170+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:45.170+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-10T00:00:00+00:00, execution_date=20250110T000000, start_date=20250111T104618, end_date=20250111T104745
[2025-01-11T11:47:45.188+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:45.187+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-10T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:47:45.212+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:45.210+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:47:45.293+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:47:45.293+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:47:45.316+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.436 seconds
[2025-01-11T11:48:00.334+0100] {processor.py:186} INFO - Started process (PID=15920) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:00.340+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:48:00.341+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:00.341+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:02.359+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592374, 'localtime': '2025-01-11 11:46'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:48:02.421+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:48:02.425+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:48:02.497+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.497+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.498+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:48:02.515+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.516+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.516+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:48:02.537+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.537+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.538+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:48:02.554+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.554+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.555+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:48:02.572+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.572+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.573+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:48:02.592+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.592+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.593+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:48:02.610+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.611+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.611+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:48:02.632+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.633+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.633+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:48:02.650+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:02.650+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:02.660+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:02.782+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:02.782+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-09T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:02.858+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:48:02.858+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:46:01.891303+00:00 end:2025-01-11 10:48:02.787725+00:00 duration:120.896422
[2025-01-11T11:48:02.859+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-09 00:00:00+00:00: scheduled__2025-01-09T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:45:54.277357+00:00. externally triggered: False>
[2025-01-11T11:48:02.859+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-09T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:02.859+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:02.859+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-09T00:00:00+00:00, execution_date=20250109T000000, start_date=20250111T104601, end_date=20250111T104802
[2025-01-11T11:48:02.871+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:02.871+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-09T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:48:02.897+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:02.896+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:48:02.986+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:02.985+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:48:03.007+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.681 seconds
[2025-01-11T11:48:06.629+0100] {processor.py:186} INFO - Started process (PID=15954) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:06.637+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:48:06.639+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:06.638+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:08.563+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592374, 'localtime': '2025-01-11 11:46'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:48:08.590+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:48:08.593+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:48:08.658+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.658+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.658+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:48:08.678+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.678+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.678+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:48:08.696+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.697+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.697+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:48:08.713+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.714+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.714+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:48:08.735+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.736+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.736+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:48:08.753+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.753+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.754+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:48:08.773+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.774+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.774+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:48:08.794+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.795+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.795+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:48:08.811+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:08.811+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:08.824+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:08.948+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:08.948+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-10T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:09.039+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:48:09.040+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:46:18.672699+00:00 end:2025-01-11 10:48:08.956329+00:00 duration:110.28363
[2025-01-11T11:48:09.040+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-10 00:00:00+00:00: scheduled__2025-01-10T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:46:10.994270+00:00. externally triggered: False>
[2025-01-11T11:48:09.040+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-10T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:09.041+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:09.040+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-10T00:00:00+00:00, execution_date=20250110T000000, start_date=20250111T104618, end_date=20250111T104808
[2025-01-11T11:48:09.052+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:09.052+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-10T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:48:09.081+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:09.080+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:48:09.185+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:09.184+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:48:09.278+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.657 seconds
[2025-01-11T11:48:24.311+0100] {processor.py:186} INFO - Started process (PID=16048) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:24.317+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:48:24.319+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:24.318+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:26.163+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592374, 'localtime': '2025-01-11 11:46'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:48:26.192+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:48:26.194+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:48:26.253+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.253+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.253+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:48:26.270+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.270+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.270+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:48:26.289+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.290+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.290+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:48:26.304+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.305+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.305+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:48:26.320+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.321+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.321+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:48:26.338+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.339+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.339+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:48:26.354+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.354+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.355+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:48:26.371+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.371+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.372+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:48:26.390+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:26.390+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:26.399+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:26.502+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:26.502+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-09T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:26.565+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:48:26.566+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:46:01.891303+00:00 end:2025-01-11 10:48:26.506384+00:00 duration:144.615081
[2025-01-11T11:48:26.566+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-09 00:00:00+00:00: scheduled__2025-01-09T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:45:54.277357+00:00. externally triggered: False>
[2025-01-11T11:48:26.566+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-09T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:26.566+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:26.566+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-09T00:00:00+00:00, execution_date=20250109T000000, start_date=20250111T104601, end_date=20250111T104826
[2025-01-11T11:48:26.580+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:26.579+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-09T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:48:26.600+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:26.600+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:48:26.682+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:26.682+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:48:26.702+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.398 seconds
[2025-01-11T11:48:30.083+0100] {processor.py:186} INFO - Started process (PID=16081) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:30.089+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:48:30.090+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:30.090+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:32.102+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736592374, 'localtime': '2025-01-11 11:46'}, 'current': {'last_updated_epoch': 1736592300, 'last_updated': '2025-01-11 11:45', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:48:32.121+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:48:32.124+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:48:32.184+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.184+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.185+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:48:32.199+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.199+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.199+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:48:32.214+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.214+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.214+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:48:32.232+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.232+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.232+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:48:32.246+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.247+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.248+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:48:32.261+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.262+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.262+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:48:32.281+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.281+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.282+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:48:32.296+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.297+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.297+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:48:32.311+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:32.311+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:32.323+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:32.448+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:32.448+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-10T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:32.516+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:48:32.516+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:46:18.672699+00:00 end:2025-01-11 10:48:32.452859+00:00 duration:133.78016
[2025-01-11T11:48:32.517+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-10 00:00:00+00:00: scheduled__2025-01-10T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:46:10.994270+00:00. externally triggered: False>
[2025-01-11T11:48:32.517+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-10T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:32.518+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:32.517+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-10T00:00:00+00:00, execution_date=20250110T000000, start_date=20250111T104618, end_date=20250111T104832
[2025-01-11T11:48:32.531+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:32.531+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-10T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:48:32.551+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:32.551+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:48:32.634+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:32.634+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:48:32.653+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.579 seconds
[2025-01-11T11:48:43.910+0100] {processor.py:186} INFO - Started process (PID=16155) to work on /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:43.917+0100] {processor.py:914} INFO - Processing file /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py for tasks to queue
[2025-01-11T11:48:43.922+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:43.922+0100] {dagbag.py:588} INFO - Filling up the DagBag from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:45.921+0100] {logging_mixin.py:190} INFO - {'location': {'name': 'Gwagwaldda', 'region': 'Federal Capital Territory', 'country': 'Nigeria', 'lat': 8.9414, 'lon': 7.0919, 'tz_id': 'Africa/Lagos', 'localtime_epoch': 1736589857, 'localtime': '2025-01-11 11:04'}, 'current': {'last_updated_epoch': 1736589600, 'last_updated': '2025-01-11 11:00', 'temp_c': 31.2, 'temp_f': 88.2, 'is_day': 1, 'condition': {'text': 'Sunny', 'icon': '//cdn.weatherapi.com/weather/64x64/day/113.png', 'code': 1000}, 'wind_mph': 4.3, 'wind_kph': 6.8, 'wind_degree': 99, 'wind_dir': 'E', 'pressure_mb': 1014.0, 'pressure_in': 29.94, 'precip_mm': 0.0, 'precip_in': 0.0, 'humidity': 19, 'cloud': 0, 'feelslike_c': 29.0, 'feelslike_f': 84.1, 'windchill_c': 31.3, 'windchill_f': 88.4, 'heatindex_c': 29.1, 'heatindex_f': 84.3, 'dewpoint_c': 0.0, 'dewpoint_f': 32.0, 'vis_km': 8.0, 'vis_miles': 4.0, 'uv': 6.5, 'gust_mph': 4.9, 'gust_kph': 7.9}}
[2025-01-11T11:48:45.946+0100] {logging_mixin.py:190} INFO - Raw data saved partitioned by date.
[2025-01-11T11:48:45.948+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:46.parquet
[2025-01-11T11:48:46.007+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.008+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:46.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.008+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:44.parquet
[2025-01-11T11:48:46.028+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.028+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:44.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.028+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:45.parquet
[2025-01-11T11:48:46.046+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.046+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:45.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.046+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:04.parquet
[2025-01-11T11:48:46.063+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.063+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:04.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.064+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:43.parquet
[2025-01-11T11:48:46.085+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.086+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:43.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.086+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-11 11:39.parquet
[2025-01-11T11:48:46.103+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.104+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-11 11:39.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.104+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:48.parquet
[2025-01-11T11:48:46.122+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.122+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:48.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.122+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 21:34.parquet
[2025-01-11T11:48:46.142+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.142+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 21:34.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.142+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 20:49.parquet
[2025-01-11T11:48:46.157+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.158+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 20:49.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.158+0100] {logging_mixin.py:190} INFO - Processing: 2025-01-07 19:56.parquet
[2025-01-11T11:48:46.177+0100] {logging_mixin.py:190} INFO - processed data saved partitioned by date.
[2025-01-11T11:48:46.177+0100] {logging_mixin.py:190} INFO - Error processing 2025-01-07 19:56.parquet: [Errno 2] No such file or directory: 'logs/processed_files.log'
[2025-01-11T11:48:46.188+0100] {processor.py:925} INFO - DAG(s) 'Temp_elt' retrieved from /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py
[2025-01-11T11:48:46.291+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:46.291+0100] {taskinstance.py:3313} ERROR - {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-10T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:46.354+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-11T11:48:46.355+0100] {logging_mixin.py:190} INFO - Task start:2025-01-11 10:46:18.672699+00:00 end:2025-01-11 10:48:46.296058+00:00 duration:147.623359
[2025-01-11T11:48:46.355+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_weather_data> dag:<DAG: Temp_elt> dagrun:<DagRun Temp_elt @ 2025-01-10 00:00:00+00:00: scheduled__2025-01-10T00:00:00+00:00, state:running, queued_at: 2025-01-11 10:46:10.994270+00:00. externally triggered: False>
[2025-01-11T11:48:46.355+0100] {logging_mixin.py:190} INFO - Failure caused by {'DAG Id': 'Temp_elt', 'Task Id': 'extract_weather_data', 'Run Id': 'scheduled__2025-01-10T00:00:00+00:00', 'Hostname': 'macbookpro'}
[2025-01-11T11:48:46.356+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:46.355+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Temp_elt, task_id=extract_weather_data, run_id=scheduled__2025-01-10T00:00:00+00:00, execution_date=20250110T000000, start_date=20250111T104618, end_date=20250111T104846
[2025-01-11T11:48:46.365+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:46.365+0100] {processor.py:876} INFO - Executed callback for <TaskInstance: Temp_elt.extract_weather_data scheduled__2025-01-10T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2025-01-11T11:48:46.390+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:46.390+0100] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T11:48:46.471+0100] {logging_mixin.py:190} INFO - [2025-01-11T11:48:46.470+0100] {dag.py:4180} INFO - Setting next_dagrun for Temp_elt to 2025-01-11 00:00:00+00:00, run_after=2025-01-12 00:00:00+00:00
[2025-01-11T11:48:46.494+0100] {processor.py:208} INFO - Processing /Users/azeez.ganiyu/airflow/dags/weather_etl_dag.py took 2.595 seconds
