[2025-01-26T16:41:51.312+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T16:41:51.329+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-26T16:41:51.339+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-24T00:00:00+00:00 [queued]>
[2025-01-26T16:41:51.339+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 6
[2025-01-26T16:41:51.375+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2025-01-24 00:00:00+00:00
[2025-01-26T16:41:51.379+0000] {standard_task_runner.py:72} INFO - Started process 87 to run task
[2025-01-26T16:41:51.382+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2025-01-24T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpekzy1h_x']
[2025-01-26T16:41:51.386+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask delete_data_from_table
[2025-01-26T16:41:51.473+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-24T00:00:00+00:00 [running]> on host b597abfab341
[2025-01-26T16:41:51.603+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-24T00:00:00+00:00'
[2025-01-26T16:41:51.605+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T16:41:51.629+0000] {sql.py:278} INFO - Executing: 
            delete from dag_runs where dt = '2025-01-24' and dag_id = 'dag_with_postgres_operator_v03';
        
[2025-01-26T16:41:51.640+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:41:51.729+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:41:51.742+0000] {sql.py:553} INFO - Running statement: 
            delete from dag_runs where dt = '2025-01-24' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2025-01-26T16:41:51.754+0000] {sql.py:562} INFO - Rows affected: 0
[2025-01-26T16:41:51.769+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T16:41:51.770+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, run_id=scheduled__2025-01-24T00:00:00+00:00, execution_date=20250124T000000, start_date=20250126T164151, end_date=20250126T164151
[2025-01-26T16:41:51.810+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T16:41:51.862+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-26T16:41:51.870+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
