[2025-01-26T16:40:26.535+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T16:40:26.549+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-26T16:40:26.564+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-21T00:00:00+00:00 [queued]>
[2025-01-26T16:40:26.565+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-26T16:40:26.603+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2025-01-21 00:00:00+00:00
[2025-01-26T16:40:26.609+0000] {standard_task_runner.py:72} INFO - Started process 576 to run task
[2025-01-26T16:40:26.614+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2025-01-21T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmprzvxrsq8']
[2025-01-26T16:40:26.618+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask delete_data_from_table
[2025-01-26T16:40:26.718+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2025-01-21T00:00:00+00:00 [running]> on host e707c27216fc
[2025-01-26T16:40:26.812+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v03' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-21T00:00:00+00:00'
[2025-01-26T16:40:26.813+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T16:40:26.831+0000] {sql.py:278} INFO - Executing: 
            delete from dag_runs where dt = '2025-01-21' and dag_id = 'dag_with_postgres_operator_v03';
        
[2025-01-26T16:40:26.842+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:40:26.922+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-01-26T16:40:26.939+0000] {sql.py:553} INFO - Running statement: 
            delete from dag_runs where dt = '2025-01-21' and dag_id = 'dag_with_postgres_operator_v03';
        , parameters: None
[2025-01-26T16:40:26.947+0000] {sql.py:562} INFO - Rows affected: 0
[2025-01-26T16:40:26.964+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T16:40:26.965+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, run_id=scheduled__2025-01-21T00:00:00+00:00, execution_date=20250121T000000, start_date=20250126T164026, end_date=20250126T164026
[2025-01-26T16:40:27.005+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T16:40:27.037+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-26T16:40:27.044+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
